### ISSUE TITLE
Support for Typescript files?

### ISSUE THREAD

**Issue by henry74** [nicolasdao/schemaglue#1]
Thanks for putting this together.  Definitely helps with organization of graph schema files and resolvers.

Tried to use this with schema files written in .ts files but had issues.  Had to switch .js files in order to use the library. Is typescript supported or planned?

**Comment by nicolasdao** [comment]
Hi @henry74 ,

Thanks heaps for your support :) We have a pretty busy roadmap at the moment. We accept pull requests though, so if you feel this is something that could add value to the GraphQL community, I'll be glad to add you as a contributor.

Let me know your thoughts.

Cheers,

Nic

**Comment by nicolasdao** [comment]
Hi @henry74 ,

Would you be able to give me an example of .ts files that are creating issues so I can add support for TypeScript?

Thanks a lot in advance.

Nic

**Comment by lukebarton** [comment]
So I tried using this via ts-node, hoping it would magically load `resolver.ts` but I was out of luck :)

**Comment by rozaydin** [comment]
+1 for the typescript support :) @nicolasdao If you havent already you can download sample ts files from [here](https://www.npmjs.com/package/@types/express-graphql)

**Comment by chrismllr** [comment]
I've opened a PR which, although it is naive, works for us! https://github.com/nicolasdao/schemaglue/pull/10

**Comment by nicolasdao** [comment]
Support for typiscript has been added in release 4.0.0 and above. Closing this issue. Thanks to @chrismllr and @ilgooz for their help.
