### ISSUE TITLE
Absolute path resolution

### ISSUE THREAD

**Issue by simlu** [nicolasdao/schemaglue#13]
Had some trouble with absolute path resolutions. E.g. I would expect something like this to work `glue(path.join(__dirname, "..", "graph"));`

Great project btw. Cheers!

**Comment by nicolasdao** [comment]
Hi @simlu ,

Thanks a lot for finding that. I'm on holidays right now. I'll have a look into that when I'm back on the 7th of August.

Thanks again. for using our lib. It means a lot to us.

Cheers,

Nic

**Comment by matteocannata** [comment]
Hi,
I had a similar issue. I'd like to use the library to run my code as npm/yarn script
node src/myScript.js

I can't do that because the lib use the cwd to compute all the file paths, so I'm forced to enter in src and then run 
node myScript.js
to make it works

**Comment by nicolasdao** [comment]
Apologies for this very late fix @matteocannata and @simlu. 

This is now fixed (latest version 4.0.4).
