### ISSUE TITLE
Support both ts and js file?

### ISSUE THREAD

**Issue by mrdulin** [nicolasdao/schemaglue#14]
I already have a lot of js files, but I want to change **only one** js file to ts.

Does it support ?

**Comment by nik-lampe** [comment]
If this is still valid and for anyone who comes to this.
I had a similar problem, needed to include .ts files in development but .js files in production.

For me it worked like this:

```
const options = {
    ignore: '**/typeDefs.?s',
    mode: '**/*.?s',
}
```
