### ISSUE TITLE
can not import ts module into js module

### ISSUE THREAD

**Issue by mrdulin** [nicolasdao/schemaglue#7]
I use `webpack` and `awesome-typescript-loader` and want to import ts module into a js file.

when I `build` my source code, it throw error.

here is the repo for reproducing this issue.

https://github.com/mrdulin/schemaglue-js-import-ts-issue

I think I know what happened. Because `schemaglue` use its `fs` operation, not use `webpack` fs oepration. So import ts module into js file will not pass webpack `loaders` and `plugins`.

**Comment by nicolasdao** [comment]
Hi @mrdulin ,

What if you add this to your webpack config:

```
node: {
   fs: "empty"
}
```
https://github.com/webpack-contrib/css-loader/issues/447

**Comment by nicolasdao** [comment]
Support for typescript added for version >= 4.0.0. Closing this issue now.
